name: Deploy мозаика62.рф

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            cd /var/www/u1538455/data/www/черкасова-юрист.рф/wp-content/themes/cherkasova-yurist
            git clone git@github.com:site100ru/cherkasova-yurist.git .
            
            #cd /var/www/u1538455/data/www/черкасова-юрист.рф/wp-content/themes/cherkasova-yurist
            #git pull